apiVersion: v1
kind: ConfigMap
metadata:
  name: livescore-demo-vertx-amqp-bridge-config
  labels:
    app: livescore-demo-vertx-amqp-bridge
    project: live-score-demo
data:
  dispatch.config: |
                  router {
                      mode: standalone
                      id: LiveScoreService
                      workerThreads: 4
                  }

                  log {
                       module: DEFAULT
                       enable: trace+
                       timestamp: true
                  }

                  listener {
                       role: normal
                       host: 0.0.0.0
                       port: amqp
                       saslMechanisms: ANONYMOUS
                  }

                  address {
                       prefix: /liveUpdates
                       distribution: multicast
                  }

                  address {
                       prefix: /setScore
                       distribution: balanced
                  }

                  address {
                       prefix: /getScore
                       distribution: balanced
                  }

                  address {
                       prefix: /addGame
                       distribution: balanced
                  }
  vertx.log.level: "TRACE"