apiVersion: v1
kind: Service
metadata:
  labels:
    name: livescore-demo-vertx-amqp-bridge
    project: live-score-demo
  name: livescore-demo-vertx-amqp-bridge
spec:
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
  selector:
    name: livescore-demo-vertx-amqp-bridge
  type: LoadBalancer

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: livescore-demo-vertx-amqp-bridge
  labels:
    project: live-score-demo
spec:
  replicas: 1
  template:
    metadata:
      name: livescore-demo-vertx-amqp-bridge
      labels:
        name: livescore-demo-vertx-amqp-bridge
        project: live-score-demo
    spec:
      containers:
        - image: scholzj/livescore-demo-vertx-amqp-bridge:latest
          name: livescore-demo-vertx-amqp-bridgedave
          imagePullPolicy: Always
          env:
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: livescore-demo-vertx-amqp-bridge-config
                  key: vertx.log.level
        - image: scholzj/qpid-dispatch:0.7.0
          name: qpid-dispatch
          imagePullPolicy: Always
          env:
            - name: QDROUTERD_CONFIG_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: livescore-demo-vertx-amqp-bridge-config
                  key: dispatch.config

          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8181
              name: https